project:
  type: book
book:
  title: Mathematics of Poker
  chapters:
  - index.qmd
  - chapters/01-poker-games-structure-and-language.qmd
  - chapters/02-counting-hands-and-boards.qmd
  - chapters/03-poker-as-a-probability-space.qmd
  - chapters/04-random-variables-expectation-and-variance.qmd
  - chapters/05-conditional-probability-and-bayes-rule.qmd
  - chapters/06-expected-value-in-multi-stage-decisions.qmd
  - chapters/07-inference-with-discrete-distributions-ranges-and-blockers.qmd
  - chapters/08-zero-sum-games-and-pure-strategies.qmd
  - chapters/09-zero-sum-games-and-mixed-strategies.qmd
  - chapters/11-betting-as-optimization.qmd
  - chapters/15-learning-equilibria-regret-minimization-and-solvers.qmd
  - chapters/13-tournament-poker-and-icm-optimization-with-nonlinear-utility.qmd
  - chapters/extension_chapter_template.qmd
  - chapters/19-learning-from-data-hand-histories-and-statistical-inference.qmd
  - chapters/Chapter_cheating_deception.qmd
  - chapters/Exploitative_vs_Equilibrium_Play.qmd
  - chapters/21-tournament_dynamics_beyond_icm.qmd
format:
  html:
    mermaid: {}
    toc: true
    number-sections: true
    html-math-method: katex

